"""Independent E8 SHORT_SCREEN contracts and no-hash source snapshots."""
import importlib.util
import json
import math
import os
from pathlib import Path
import shutil
import sys

import yaml

COEFFICIENTS={'N':0.,'C0':.1,'C1':0.09227393550836771}
ENDPOINT='SHORT_SCREEN_E8_LAST_EMA'


def read(path):return json.loads(Path(path).read_text(encoding='utf-8'))


def write_new(path,value):
    with Path(path).open('x',encoding='utf-8') as f:
        json.dump(value,f,ensure_ascii=False,indent=2,allow_nan=False);f.write('\n')


def stat(path):
    path=Path(path);s=path.stat()
    return dict(path=str(path.resolve()),bytes=s.st_size,mtime_ns=s.st_mtime_ns)


def validate_config(cfg):
    arm=cfg.get('arm')
    if arm not in COEFFICIENTS:raise ValueError('Only short N/C0/C1 allowed')
    for key,value in dict(dataset='dronevehicle',seed=42,epochs=8,expected_nc=5,imgsz=640,batch=32,nbs=64,
                           workers=4,expected_train_images=17990,expected_val_images=1469,amp=True,
                           classification_coefficient=COEFFICIENTS[arm],localization_coefficient=0.).items():
        if cfg.get(key)!=value:raise ValueError('SHORT_SCREEN config differs: '+key)
        if type(value) in (int,bool) and type(cfg.get(key)) is not type(value):raise ValueError('Wrong config type: '+key)
    s=cfg.get('short_screen',{})
    if (s.get('scope')!='SHORT_SCREEN' or s.get('single_seed') is not True or s.get('endpoint')!=ENDPOINT
        or s.get('scheduler_horizon_epochs')!=8 or s.get('comparison_arms')!=list(COEFFICIENTS)
        or s.get('full_dev_gt_objects')!=22462 or cfg.get('formal_training_authorized') is not False):
        raise ValueError('Separate short-screen scope required')
    if Path(cfg['model']).name!='yolo11n.pt':raise ValueError('Original yolo11n initialization required')
    return cfg


def load_config(path):return validate_config(yaml.safe_load(Path(path).read_text(encoding='utf-8')))


def data_output(path):
    path=Path(path).resolve()
    if os.name!='posix' or not str(path).startswith('/mnt/dataset/yudongfang/'):
        raise ValueError('Execution output must be a new project data-disk directory')
    return path


def explicit(name,path):
    spec=importlib.util.spec_from_file_location(name,path);mod=importlib.util.module_from_spec(spec)
    sys.modules[name]=mod;spec.loader.exec_module(mod);return mod


def copy_sources(output,paths):
    dest=output/'source_copies';dest.mkdir(exist_ok=False);rows=[]
    for i,p in enumerate(sorted({Path(p).resolve() for p in paths},key=str)):
        target=dest/('%04d_'%i+p.name);shutil.copyfile(p,target)
        if p.read_bytes()!=target.read_bytes():raise AssertionError('Source byte copy differs')
        rows.append(dict(stat(p),copy=str(target),byte_identity=True))
    write_new(output/'source_manifest.json',dict(new_hash_computed=False,files=rows))


def require_admission(path,cfg,config_path,entry_path,stage):
    """No such receipt is generated by this release package.

    Root must independently review/create a decision with actual evidence. A
    recorded 24-update diagnostic alone is deliberately insufficient.
    """
    if path is None:raise ValueError('E8 cannot run: actual SHORT_SCREEN admission is absent')
    a=read(path)
    if (a.get('status')!='SHORT_SCREEN_ADMITTED' or a.get('scope')!='SINGLE_SEED_E8_SCREEN_ONLY'
        or a.get('queue_authorized') is not True or a.get('formal_e200_authorized') is not False
        or a.get('arm')!=cfg['arm'] or a.get('seed')!=42 or a.get('epochs')!=8):
        raise ValueError('Invalid SHORT_SCREEN admission')
    for actual,key in [(Path(config_path),'approved_config_copy'),(Path(entry_path),'approved_'+stage+'_entry_copy')]:
        if actual.read_bytes()!=Path(a[key]).read_bytes():raise ValueError('Approved bytes differ: '+key)
    tech=read(a['technical_review'])
    budget=read(a['resource_budget_review'])
    if (tech.get('status')!='PASS_FOR_SHORT_SCREEN' or tech.get('arm')!=cfg['arm']
        or tech.get('new_successful_updates',0)<24 or tech.get('candidate_source_reviewed') is not True):
        raise ValueError('New 24-update/implementation review not accepted for this screen')
    if budget.get('status')!='PASS_FOR_SHORT_SCREEN_RESOURCE_AND_BUDGET' or budget.get('globallease_required') is not True:
        raise ValueError('Measured resource/budget review required')
    for key in ('measured_training_nvml_peak_mib','measured_training_rss_peak_mib','estimated_three_arm_seconds_with_margin'):
        v=budget.get(key)
        if type(v) not in (int,float) or not math.isfinite(v) or v<=0:raise ValueError('Missing finite measured budget: '+key)
    if budget['estimated_three_arm_seconds_with_margin']>43200:raise ValueError('Not within reviewed 12-hour budget')
    # The referenced real update artifact must exist; its interpretation is the
    # independent technical review's responsibility, not an invented auto-PASS.
    evidence=Path(tech['new_update_evidence'])
    if not evidence.is_file():raise FileNotFoundError(evidence)
    return a
