weights: /mnt/dataX/ydf/projects/RGBT_campaign_90/external_reproductions/cft/author_initialization/yolov5l.pt
cfg: ''
data: /mnt/dataX/ydf/projects/RGBT_campaign_90/data_author_protocol/llvip_baseline_attempt1/visible/data.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 200
batch_size: 8
imgsz: 1280
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: /mnt/dataX/ydf/projects/RGBT_campaign_90/artifacts/original_repro_continue_20260909_attempt1/llvip_train_canary_attempt2
name: author_train
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 0
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: /mnt/dataX/ydf/projects/RGBT_campaign_90/artifacts/original_repro_continue_20260909_attempt1/llvip_train_canary_attempt2/author_train
