weights: /mnt/dataX/ydf/projects/RGBT_campaign_90/external_reproductions/cft/author_initialization/yolov5l.pt
cfg: /mnt/dataX/ydf/projects/RGBT_campaign_90/external_reproductions/cft/author_source/models/transformer/yolov5l_fusion_transformerx3_llvip.yaml
data: /mnt/dataX/ydf/projects/RGBT_campaign_90/data_author_protocol/llvip_attempt1/previous/LLVIP.yaml
hyp: /mnt/dataX/ydf/projects/RGBT_campaign_90/external_reproductions/cft/author_source/data/hyp.scratch.yaml
epochs: 200
batch_size: 32
total_batch_size: 32
img_size:
- 1024
- 1024
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: 0,1
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: /mnt/dataX/ydf/projects/RGBT_campaign_90/artifacts/cft_author_protocol_20260909_attempt1/train_canary32_dp_attempt1
entity: null
name: author_train_canary
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: /mnt/dataX/ydf/projects/RGBT_campaign_90/artifacts/cft_author_protocol_20260909_attempt1/train_canary32_dp_attempt1/author_train
